{% set version = "5.2.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tesseract
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tesseract_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tesseract/tesseract_{{ version }}.tar.gz
  sha256: 8ab635151e2408cccdc3f028ba01ef0115d9be26a878e14186fde1fd8b7e68eb
  patches:
    - patches/0001-add-pthread.patch

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-curl
    - r-digest
    - r-pdftools >=1.5
    - r-rappdirs
    - tesseract >=3.03            # [not win]
    - leptonica                   # [win]
  run:
    - r-base
    - r-rcpp >=0.12.12
    - r-curl
    - r-digest
    - r-pdftools >=1.5
    - r-rappdirs
    - tesseract >=3.03            # [not win]

test:
  commands:
    - $R -e "library('tesseract')"           # [not win]
    - "\"%R%\" -e \"library('tesseract')\""  # [win]

about:
  home: https://github.com/ropensci/tesseract
  license: Apache-2.0
  summary: "Bindings to 'Tesseract' (https://opensource.google.com/projects/tesseract):  a powerful optical character recognition (OCR) engine that supports over 100 languages. The engine is highly configurable in order to tune the detection algorithms and obtain the best possible results."
  license_family: APACHE
  license_file:
    - LICENSE
    - inst/COPYRIGHT

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
